# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b0ae97a3916ff25bce8cc0d6eba8b9f5b58e80a026c4ce1f525781d7d28afc79b925e039271fb16a1774107b312600ca1ed61207cc669102a577d9ef24ee72c

test:
  secret_key_base: ccffac3bf5447d4da129e6b10da60355daccbff61386528c9235071515f60e84b4908bb32b90ccb3485cc87cb35ce7f63fe5e9ca8be8666598d8337188835180

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
